#!/usr/bin/env python

"""
This script serves as the command-line entry point for the Greengraph package.
It processes user input for evaluating green space between two locations and generates
a graphical output showing the green pixels at regular intervals along the journey.
"""

from Greengraph.command import process

if __name__ == "__main__":
    process()